name:                progress-email
version:             0.1.0.0
github:              "githubuser/progress-email"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/progress-email#readme>

dependencies:
- base >= 4.7 && < 5
- formatting
- classy-prelude
- time
- text
- optparse-applicative
- aeson

library:
  source-dirs: src

